@startuml superMario

class Usuario
class Mario
class Luigi
class PrincesaPeach
class PrincesaDaisy
class Toad
class Yoshi
class Bowser
class BowserJr
class Koopa
class Goomba
class Paragoomba
class Lakitu
class Spiny
class PiranhaPlant
class Boo
class ShyGuy
class BobOmb
class ChainChomp
class Thwomp
class HammerBro
class Blooper
class CheepCheep
class BulletBill
class PowerUp
class Champinon
class FlorDeFuego
class Estrella
class Moneda
class Bloque
class Tuberia
class Item
class Vida

Entidad <|-- Personaje
Personaje <|-- Enemigo

Personaje <|-- Mario
Personaje <|-- Luigi
Personaje <|-- PrincesaPeach
Personaje <|-- PrincesaDaisy
Personaje <|-- Toad
Personaje <|-- Yoshi
Personaje <|-- Bowser
Personaje <|-- BowserJr

Enemigo <|-- Koopa
Enemigo <|-- Goomba
Enemigo <|-- Paragoomba
Enemigo <|-- Lakitu
Enemigo <|-- Spiny
Enemigo <|-- PiranhaPlant
Enemigo <|-- Boo
Enemigo <|-- ShyGuy
Enemigo <|-- BobOmb
Enemigo <|-- ChainChomp
Enemigo <|-- Thwomp
Enemigo <|-- HammerBro
Enemigo <|-- Blooper
Enemigo <|-- CheepCheep
Enemigo <|-- BulletBill

Personaje "1" *-- "0..3" Vida
Mario "1" *-- "0..1" PowerUp
Luigi "1" *-- "0..1" PowerUp
PowerUp <|-- Champinon
PowerUp <|-- FlorDeFuego
PowerUp <|-- Estrella

Mario "1" o-- "0..99" Moneda
Luigi "1" o-- "0..99" Moneda

Mundo "1" *-- "1..*" Bloque
Mundo "1" *-- "1..*" Tuberia
Mundo "1" *-- "0..*" Enemigo

Bloque "1" o-- "1..12" Moneda
Bloque "1" o-- "0..1" PowerUp

class Mario{
    + Recoger(Item)
}

class Koopa {
    - Vida vida
    + Morir()
}

class Bloque{
    - Item contenido
    + Item : Explotar()
}

class Goomba{
    - Vida vida
    + Morir()
}


@enduml