@startuml superMarioBros

class Usuario
class Personaje
class Heroe
class Enemigo
class Jefe
class Item
class Partida
class Puntos

class Mario
class Luigi
class Peach
class Daisy
class Toad

class PowerUp
class Champinon
class FlorFuego
class Estrella
class Moneda
class Bloque
class Tuberia

class Mundo
class Vida
class Nivel
class Temporizador
class Segundo

class Bowser
class BowserJr
class Koopa
class Goomba
class Paragoomba
class Lakitu
class Spiny
class PiranhaPlant
class Boo
class ShyGuy
class BobOmb
class ChainChomp
class Thwomp
class HammerBro
class Blooper
class CheepCheep
class BulletBill

Personaje <|-- Enemigo
Personaje <|-- Heroe
Personaje <|-- Jefe
Item <|-- PowerUp
Item <|-- Moneda
PowerUp <|-- Champinon
PowerUp <|-- FlorFuego
PowerUp <|-- Estrella

Heroe <|-- Mario
Heroe <|-- Luigi
Heroe <|-- Peach
Heroe <|-- Daisy
Heroe <|-- Toad

Jefe <|-- Bowser
Jefe <|-- BowserJr

Enemigo <|-- Koopa
Enemigo <|-- Goomba
Enemigo <|-- Paragoomba
Enemigo <|-- Lakitu
Enemigo <|-- Spiny
Enemigo <|-- PiranhaPlant
Enemigo <|-- Boo
Enemigo <|-- ShyGuy
Enemigo <|-- BobOmb
Enemigo <|-- ChainChomp
Enemigo <|-- Thwomp
Enemigo <|-- HammerBro
Enemigo <|-- Blooper
Enemigo <|-- CheepCheep
Enemigo <|-- BulletBill

Usuario "1" *-- "1" Heroe
Usuario "1" o-- "0..3" Partida

Enemigo "1" *-- "0..1" Vida
Jefe "1" *-- "0..3" Vida

Nivel "1" *-- "1" Heroe
Nivel "1" *-- "1..*" Bloque
Nivel "1" *-- "1..*" Tuberia
Nivel "1" *-- "0..*" Enemigo
Nivel "1" *-- "1" Temporizador

Temporizador "1" *-- "0..160" Segundo

Mundo "1" o-- "0..4" Nivel
Mundo "1" *-- "1" Jefe

Heroe "1" o-- "1" Item
Heroe "1" o-- "0..1" PowerUp
Heroe "1" o-- "0..99" Moneda
Heroe "1" o-- "0..1" Tuberia
Heroe "1" o-- "0..*" Enemigo
Heroe "1" o-- "0..1" Jefe
Heroe "1" o-- "0..*" Bloque
Heroe "1" *-- "0..99" Vida

Bloque "1" o-- "1..12" Moneda
Bloque "1" o-- "0..1" PowerUp

Partida "1" *-- "1" Nivel
Partida "1" *-- "0..*" Puntos

class Usuario {
    - Heroe heroe
}

class Partida{
    - Nivel nivel
    + Guardar(Nivel)
    + Cargar() : Nivel
    + Pausar()
}

class Heroe {
    + Saltar()
    + Agachar()
    + Correr()
    + Recoger(Item)
    + RecibirDano()
    + EntrarTuberia(Tuberia)
}
class Enemigo{
    + Morir()
    + RecibirDano(Heroe)
}
class Jefe{
    + RecibirDano(Heroe)
    + Activar()
    + Enfurecer()
}

class Bloque{
    + Golpear(Heroe)
}

class Tuberia {
    + Ingresar(Heroe) : Nivel
}

class Moneda {
    + SumarPuntos(Moneda) : Puntos
}

class PowerUp {
    + Activar(Heroe)
    + Liberar() : Item
}

class Nivel {
    + IniciarNivel()
    + FinalizarNivel()
    + Pausar()
    + AvanzarNivel()
    + DerrotarJefeMundo()
}

class Temporizador {
    - Segundo segundo
}

@enduml