@startuml superMarioBros

class Usuario
class Personaje
class Heroe
class Enemigo
class Jefe
class Item

class Mario
class Luigi
class PrincesaPeach
class PrincesaDaisy
class Toad

class PowerUp
class Champinon
class FlorFuego
class Estrella
class Moneda
class Bloque
class Tuberia
class Item

class Mundo
class Vida
class Nivel
class Temporizador
class Segundo

class Bowser
class BowserJr
class Koopa
class Goomba
class Paragoomba
class Lakitu
class Spiny
class PiranhaPlant
class Boo
class ShyGuy
class BobOmb
class ChainChomp
class Thwomp
class HammerBro
class Blooper
class CheepCheep
class BulletBill

Personaje <|-- Enemigo
Personaje <|-- Heroe
Personaje <|-- Jefe
Item <|-- PowerUp
Item <|-- Moneda

Heroe <|-- Mario
Heroe <|-- Luigi
Heroe <|-- PrincesaPeach
Heroe <|-- PrincesaDaisy
Heroe <|-- Toad

Jefe <|-- Bowser
Jefe <|-- BowserJr

Enemigo <|-- Koopa
Enemigo <|-- Goomba
Enemigo <|-- Paragoomba
Enemigo <|-- Lakitu
Enemigo <|-- Spiny
Enemigo <|-- PiranhaPlant
Enemigo <|-- Boo
Enemigo <|-- ShyGuy
Enemigo <|-- BobOmb
Enemigo <|-- ChainChomp
Enemigo <|-- Thwomp
Enemigo <|-- HammerBro
Enemigo <|-- Blooper
Enemigo <|-- CheepCheep
Enemigo <|-- BulletBill

PowerUp <|-- Champinon
PowerUp <|-- FlorDeFuego
PowerUp <|-- Estrella

Usuario "1" o-- "1" Heroe

Enemigo "1" *-- "0..1" Vida
Jefe "1" *-- "0..3" Vida
Heroe "1" *-- "0..99" Vida
Heroe "1" o-- "1" Vida
Enemigo "1" o-- "1" Vida
Jefe "1" o-- "1" Vida
Nivel "1" *-- "1" Heroe

Heroe "1" o-- "0..1" PowerUp

Heroe "1" o-- "0..99" Moneda
Heroe "1" o-- "1" Tuberia
Nivel "1" *-- "1" Heroe
Nivel "1" *-- "1..*" Bloque
Nivel "1" *-- "1..*" Tuberia
Nivel "1" *-- "0..*" Enemigo

Nivel *-- Temporizador
Temporizador "1" *-- "0..160" Segundo

Mundo "1" o-- "0..4" Nivel
Mundo "1" *-- "1" Jefe

Bloque "1" o-- "1..12" Moneda
Bloque "1" o-- "0..1" PowerUp

class Usuario {
    - Heroe heroe
    + GuardarPartida(Nivel)
    + CargarPartida(Nivel)
    + SeleccionarHeroe(Heroe)
}

class Vida{
    + Perder(Vida)
    + Ganar(Vida)
}

class Personaje{
    + Caminar()
    + Caer()
    - Vida vida
}

class Heroe{
    - Tuberia tuberia
    + Item item
    - PowerUp poweUp
    + saltar()
    + agacharse()
    + correr()
    + recoger(Item)
    + recibirDano()
    + entrarTuberia(Tuberia)
}

class Enemigo {
    + Morir()
    + Atacar()
    + CambiarDireccion()
}

class Jefe {
    + UsarHabilidadEspecial()
    + Enfurecer()
}

class Bloque{
    - Item contenido
    + Golpear()
    + Item : 
}

class Tuberia{
    + Nivel : Ingresar(Heroe)
    - Nivel entrada
    - Nivel salida
}

class Moneda{
    + Puntos : SumarPuntos(Monedas)
}

class PowerUp{
    + activar(Heroe)
    + Liberar() : Item
}

class Mundo {
    + iniciarNivel()
    + avanzarNivel()
    + derrotarJefeMundo()
}

class Nivel {
    + IniciarNivel()
    + FinalizarNivel()
    + Pausar()
    + IniciarNivel()
    + AvanzarNivel()
    + DerrotarJefeMundo()
}

class Temporizador {
    - Segundo segundo
    + Iniciar()
    + Detener()
}

@enduml